### PR TITLE
Fixes and cleanups

### PR DESCRIPTION
**Pull request by remcohaszing**
I broke the build in #38, so I reverted this. I also did some chores. I split it up into small commits so you can see what’s going on.

The umd example doesn’t work for me, but it didn’t work before either.

### CODE REVIEW

**Comment by fleon** [comment]
Thanks for your contribution @remcohaszing. I will take a look at this PR over the weekend.

**Comment by remcohaszing** [comment]
@fleon have you had time to look at this yet? No pressure, I just don’t want this to be forgotten. :)

**Comment by fleon** [comment]
I will take a look at this today. Thanks for your patience.

**Comment by fleon** [comment]
Thanks for the contribution @remcohaszing. LGTM!

**Pull request merged**
